### ISSUE TITLE
Please Review this incident as soon as possible Fix Bug in the first feature

### ISSUE THREAD

**Issue by YonasAsres** [YonasAsres/GitMasteryChallenge#3]
please answer the following git questions 

- [ ] Understanding the difference between "Fetch" and "Pull"
- [ ] Restoring a previous version of your project
- [ ] this is whats going on #1 
- [ ] and please review the following #2

**Comment by YonasAsres** [comment]
@Issyeu  please check this if there is any update.

**Comment by Issyeu** [comment]
@YonasAsres  ok yoni i will check for updates

**Comment by Issyeu** [comment]
now it is done @YonasAsres  have a nice time
